Algoritmo "Entrada e saída de dados"

// Descrição   : Entrada e saída de dados
// Autor(a)    : Júlio Reis
// Data atual  : 15/12/2021
Var
// Seção de Declarações das variáveis 
   nome: caracter
   nota: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva("Informe seu nome:")
   leia(nome)
   escreva("Informe sua idade:")
   leia(nota)
   
   escreval("Nome: ",nome)
   escreval("Nota: ",nota)

Fimalgoritmo