Algoritmo "Estrutura para faça 2"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 16/12/2021
Var
   // Seção de Declarações das variáveis
   numero, fatorial, contador: inteiro
   
Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreva("Digite um número para calcular o fatorial: ")
   leia(numero)
   fatorial := 1
   para contador de 1 até numero faca
        fatorial := fatorial * contador
   fimpara
   escreva("O fatorial de ", numero, " é: ", fatorial)
Fimalgoritmo