Algoritmo "Estrutura para-faça"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 

// Descrição   : Calcula dois valores e realiza operação entre eles
// Autor(a)    : Júlio Reis
// Data atual  : 15/12/2021
Var
   // Seção de Declarações das variáveis
   numero, fatorial, contador: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreva("Digite o número para lcular o fatorial:")
   leia(numero)
   fatorial := 1
   para contador de 1 até numero faca
        fatorial := fatorial * contador
   fimpara
   escreva("O fatorial de ", numero, " é: ", fatorial)


Fimalgoritmo