Algoritmo "Operadores relacionais"

// Descrição   : Operadores Aritméticos
// Autor(a)    : Júlio Reis
// Data atual  : 15/12/2021
Var
// Seção de Declarações das variáveis
nota1, nota2: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
nota1 := 10
nota2 := 15

se (nota1 <> nota2) entao
//se (nota1 = nota2) entao
//se (nota1 <= nota2) entao
//se (nota1 >= nota2) entao
   escreval("Nota1 é diferente")
senao
     escreval("Nota1 é igual")
fimse

Fimalgoritmo